### ISSUE TITLE
2dmatch: scrutinees are backwards from documentation

### ISSUE THREAD

**Issue by stamourv** [racket/2d#1]
The `match2d` docs state that, in the top-left cell, scrutinees are arranged as follows:

```
╔═════════════════╗
║col-expr row-expr║
╚═════════════════╝
```

I.e., the left scrutinee is matched against the first column's patterns, and the right one is matched against the first row's patterns.

That's not what's happening.

```
#2dmatch
╔══════╦═══╦═══╗
║ 1  3 ║ 3 ║ 4 ║
╠══════╬═══╬═══╣
║ 1    ║'a ║'b ║
╠══════╬═══╬═══╣
║ 2    ║'c ║'d ║
╚══════╩═══╩═══╝
```

`=> 2dmatch: no matching clause for '(1 3)`

The tests arrange scrutinees on separate lines, which puts `col` on the left, but after `row`, and so they pass:

```
 #2dmatch
 ╔════════╦═══╗
 ║      3 ║ x ║
 ║ 1      ║   ║
 ╠════════╬═══╣
 ║   2    ║   ║
 ╠════════╣ x ║
 ║   1    ║   ║
 ╚════════╩═══╝
```

We could either fix the docs to be the right way around (and suggest the separate lines trick), and fix the example (which currently works backwards). Or we could change the parsing to decide `row` and `col` based on the starting column of each piece of syntax.

**Comment by rfindler** [comment]
I like the starting column idea. There are a few of these in the main-distribution; I think that if they all continue to work properly with the starting column approach, then that's the way to go.

Another approach would be to factor in the starting line of each somehow?

**Comment by stamourv** [comment]
Fixed.
The new approach also allows the column scrutinee to be directly below the row scrutinee, as you suggested.
