### ISSUE TITLE
Please support emacs table-mode defaults

### ISSUE THREAD

**Issue by jeapostrophe** [racket/2d#5]
By default table-mode, doesn't used the double-barred versions of the characters and just uses +, -, and |.

Even if you change the defaults to what Racket expects
```
(setq table-cell-horizontal-chars "═")
(setq table-cell-vertical-char ?║)
(setq table-cell-intersection-char ?╬)
```

Then 2d parse still fails because table-mode considers the corners to be intersections.

Given that table-mode is heavily supported in lots of other emacs modes, like org and ledger, it would be nice for it to be easily Racketable.

I looked into the code to make this change myself but it was too hard for me. I couldn't tell where the corner was actually specified. If you help me out, I can try to make the change.

https://www.emacswiki.org/emacs/TableMode

**Comment by rfindler** [comment]
That's a big change to the parser.

**Comment by jeapostrophe** [comment]
I don't really understand why. (I guess that's why I couldn't read the code to change it. I expected to just see something that look for a corner character and that created a new column/row, but I didn't see anything like that.) Is it because of the cool-shaped-cells that 2dcond supports?

**Comment by rfindler** [comment]
I guess I shouldn't speculate on how hard it would be. But you're definitely taking away information from the parser and that doesn't sound simple.

In any case, the way the parser works is by finding the first line (skipping past whitespace, basically) and then reading it. It makes it contains only "top" characters and then it uses those as the guide posts for parsing subsequent lines.

This is the first line parser:

https://github.com/racket/2d/blob/master/2d-lib/private/read-util.rkt#L349

and the subsequent lines parser follows that.

So it doesn't support this, either:

```
╔═════╦═════╗
║     ║     ║
╠═════╬═══╦═╣
║     ║   ║ ║
╚═════╩═══╩═╝
```

**Comment by jeapostrophe** [comment]
Alright it works REALLY differently than I thought. I think the simpler thing is for me to make emacs produce this format :)

**Comment by rfindler** [comment]
I was thinking that it seemed easier to make Emacs produce that format too, but I didn't dare suggest it. :)

**Comment by togakangaroo** [comment]
@jeapostrophe you ever build an emacs mode for this?

**Comment by jeapostrophe** [comment]
Nope
